version: '3'
services:
  db:
    image: mysql/mysql-server
    ports:
      - "3305:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "MYSQL_USER=${DB_USER}"
      - "MYSQL_PASSWORD=${DB_PASSWORD}"
      - "MYSQL_DATABASE=${DB_NAME}"   
  web:
    build:
      context: API/.
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - "db:database"